# This is a Docker Compose file for the InfluxData documentation site.
## Run documentation tests for code samples.
name: influxdata-docs
services:
  link-check:
    image: lycheeverse/lychee
    depends_on:
      local-dev:
        condition: service_healthy
    command:
      # Stay offline and block network requests.
      # - --offline
      # List found links without checking them (useful for debugging).
      # - --dump
      - --include-fragments
      - --base
      - http://local-dev:1313/
      - --include
      # Include any URLs that end in slash (no .css, .js).
      - http://local-dev:1313/.*\/$
      - --include
      # Include link paths that contain a hash (#).
      - http://local-dev:1313/.*#.*$
      # Remap any localhost URLs to the local-dev service hostname.
      - --remap
      - "http://localhost:1313 http://local-dev:1313"
      # List of URLs to check.
      - http://local-dev:1313/chronograf/v1/
      - http://local-dev:1313/enterprise_influxdb/v1/
      - http://local-dev:1313/flux/v0/
      - http://local-dev:1313/influxdb/cloud/
      - http://local-dev:1313/influxdb/cloud-dedicated/
      - http://local-dev:1313/influxdb/cloud-serverless/
      - http://local-dev:1313/influxdb/clustered/
      - http://local-dev:1313/influxdb/v2/
      - http://local-dev:1313/kapacitor/v1/
      - http://local-dev:1313/telegraf/v1/
      # Check links in HTML files (instead of over HTTP)
           # - /public/**/*.html
    profiles:
      - lint
    stdin_open: true
    tty: true
    working_dir: / 
    volumes:
      - type: bind
        source: ./public
        target: /public
  ## Run InfluxData documentation with the hugo development server on port 1313.
  ## For more information about the hugomods/hugo image, see
  ## https://docker.hugomods.com/docs/development/docker-compose/
  local-dev:
    build:
      context: . 
      dockerfile_inline: |
        FROM hugomods/hugo:exts-0.123.8
        RUN apk add --no-cache curl openssl
    command: hugo server --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1313/influxdb/cloud-dedicated/"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 40s
      start_interval: 5s
    ports:
      - 1313:1313
    volumes:
      - type: bind
        source: "$PWD"
        target: /src
      - type: bind
        source: $HOME/hugo_cache
        target: /tmp/hugo_cache
    profiles:
      - local
      - lint
  cloud-pytest:
    image: influxdata/docs-pytest
    build:
      args:
        - CONTENT_PATH=content/influxdb/cloud
      context: .
      dockerfile: Dockerfile.pytest
    entrypoint:
      - /bin/bash
      - /src/test/scripts/run-tests.sh
      - pytest
    command:
      # In the command, pass file paths to test.
      # The container preprocesses the files for testing and runs the tests.
      - content/influxdb/cloud/**/*.md
    profiles:
      - test
      - v2
    stdin_open: true
    tty: true
    volumes:
      # Site configuration files.
      - type: bind
        source: .
        target: /src
        read_only: true
      # Files shared between host and container and writeable by both.
      - type: bind
        source: ./test/shared
        target: /shared
      - type: bind
        source: ./content/influxdb/cloud/.env.test
        target: /app/.env.test
        read_only: true
      # In your code samples, use `/app/data/<FILE.lp>` or `data/<FILE.lp>` to access sample data files from the `static/downloads` directory. 
      - type: bind
        source: ./static/downloads
        target: /app/data
        read_only: true
      # In your code samples, use `/app/iot-starter` to store example modules or project files.
      - type: volume
        source: cloud-tmp
        target: /app/iot-starter
      # Target directory for the content under test.
      # Files are copied from /src/content/<productpath> to /app/content/<productpath> before running tests.
      - type: volume
        source: test-content
        target: /app/content
    working_dir: /app
  cloud-dedicated-pytest:
    image: influxdata/docs-pytest
    build:
      args:
        - CONTENT_PATH=content/influxdb/cloud-dedicated
      context: .
      dockerfile: Dockerfile.pytest
    entrypoint:
      - /bin/bash
      - /src/test/scripts/run-tests.sh
      - pytest
    command:
      # In the command, pass file paths to test.
      # The container preprocesses the files for testing and runs the tests.
      - content/influxdb/cloud-dedicated/**/*.md
    profiles:
      - test
      - v3
    stdin_open: true
    tty: true
    volumes:
      # Site configuration files.
      - type: bind
        source: .
        target: /src
        read_only: true
      # Files shared between host and container and writeable by both.
      - type: bind
        source: ./test/shared
        target: /shared
      - type: bind
        source: ./content/influxdb/cloud-dedicated/.env.test
        target: /app/.env.test
        read_only: true
      # The following mount assumes your influxctl configuration file is located at ./content/influxdb/cloud-dedicated/config.toml.
      - type: bind
        source: ./content/influxdb/cloud-dedicated/config.toml
        target: /root/.config/influxctl/config.toml
        read_only: true
      # In your code samples, use `/app/data/<FILE.lp>` or `data/<FILE.lp>` to access sample data files from the `static/downloads` directory. 
      - type: bind
        source: ./static/downloads
        target: /app/data
        read_only: true
      # In your code samples, use `/app/iot-starter` to store example modules or project files.
      - type: volume
        source: cloud-dedicated-tmp
        target: /app/iot-starter
      # Target directory for the content under test.
      # Files are copied from /src/content/<productpath> to /app/content/<productpath> before running tests.
      - type: volume
        source: test-content
        target: /app/content
    working_dir: /app
  cloud-serverless-pytest:
    image: influxdata/docs-pytest
    build:
      args:
        - CONTENT_PATH=content/influxdb/cloud-serverless
      context: .
      dockerfile: Dockerfile.pytest
    entrypoint:
      - /bin/bash
      - /src/test/scripts/run-tests.sh
      - pytest
    command:
      # In the command, pass file paths to test.
      # The container preprocesses the files for testing and runs the tests.
      - content/influxdb/cloud-serverless/**/*.md
    profiles:
      - test
      - v3
    stdin_open: true
    tty: true
    volumes:
      # Site configuration files.
      - type: bind
        source: .
        target: /src
        read_only: true
      # Files shared between host and container and writeable by both.
      - type: bind
        source: ./test/shared
        target: /shared
      - type: bind
        source: ./content/influxdb/cloud-serverless/.env.test
        target: /app/.env.test
        read_only: true
      # In your code samples, use `/app/data/<FILE.lp>` or `data/<FILE.lp>` to access sample data files from the `static/downloads` directory. 
      - type: bind
        source: ./static/downloads
        target: /app/data
        read_only: true
      # In your code samples, use `/app/iot-starter` to store example modules or project files.
      - type: volume
        source: cloud-serverless-tmp
        target: /app/iot-starter
      # Target directory for the content under test.
      # Files are copied from /src/content/<productpath> to /app/content/<productpath> before running tests.
      - type: volume
        source: test-content
        target: /app/content
    working_dir: /app
  clustered-pytest:
    image: influxdata/docs-pytest
    build:
      args:
        - CONTENT_PATH=content/influxdb/clustered
      context: .
      dockerfile: Dockerfile.pytest
    entrypoint:
      - /bin/bash
      - /src/test/scripts/run-tests.sh
      - pytest
    command:
      # In the command, pass file paths to test.
      # The container preprocesses the files for testing and runs the tests.
      - content/influxdb/clustered/**/*.md
    profiles:
      - test
      - v3
    stdin_open: true
    tty: true
    volumes:
      # Site configuration files.
      - type: bind
        source: .
        target: /src
        read_only: true
      # Files shared between host and container and writeable by both.
      - type: bind
        source: ./test/shared
        target: /shared
      - type: bind
        source: ./content/influxdb/clustered/.env.test
        target: /app/.env.test
        read_only: true
      # The following mount assumes your influxctl configuration file is located at ./content/influxdb/clustered/config.toml.
      - type: bind
        source: ./content/influxdb/clustered/config.toml
        target: /root/.config/influxctl/config.toml
        read_only: true
      # In your code samples, use `/app/data/<FILE.lp>` or `data/<FILE.lp>` to access sample data files from the `static/downloads` directory. 
      - type: bind
        source: ./static/downloads
        target: /app/data
        read_only: true
      # In your code samples, use `/app/iot-starter` to store example modules or project files.
      - type: volume
        source: clustered-tmp
        target: /app/iot-starter
      # Target directory for the content under test.
      # Files are copied from /src/content/<productpath> to /app/content/<productpath> before running tests.
      - type: volume
        source: test-content
        target: /app/content
    working_dir: /app
  telegraf-pytest:
    image: influxdata/docs-pytest
    build:
      args:
        - CONTENT_PATH=content/telegraf
      context: .
      dockerfile: Dockerfile.pytest
    entrypoint:
      - /bin/bash
      - /src/test/scripts/run-tests.sh
      - pytest
    command:
      # In the command, pass file paths to test.
      # The container preprocesses the files for testing and runs the tests.
      - content/telegraf/**/*.md
    profiles:
      - test
    stdin_open: true
    tty: true
    volumes:
      # Site configuration files.
      - type: bind
        source: .
        target: /src
        read_only: true
      # Files shared between host and container and writeable by both.
      - type: bind
        source: ./test/shared
        target: /shared
      - type: bind
        source: ./content/telegraf/.env.test
        target: /app/.env.test
        read_only: true
      # In your code samples, use `/app/data/<FILE.lp>` or `data/<FILE.lp>` to access sample data files from the `static/downloads` directory. 
      - type: bind
        source: ./static/downloads
        target: /app/data
        read_only: true
      # In your code samples, use `/app/iot-starter` to store example modules or project files.
      - type: volume
        source: telegraf-tmp
        target: /app/iot-starter
      # Target directory for the content under test.
      # Files are copied from /src/content/<productpath> to /app/content/<productpath> before running tests.
      - type: volume
        source: test-content
        target: /app/content
    working_dir: /app
  v2-pytest:
    image: influxdata/docs-pytest
    build:
      args:
        - CONTENT_PATH=content/influxdb/v2
      context: .
      dockerfile: Dockerfile.pytest
    entrypoint:
      - /bin/bash
      - /src/test/scripts/run-tests.sh
      - pytest
    command:
      # In the command, pass file paths to test.
      # The container preprocesses the files for testing and runs the tests.
      - content/influxdb/v2/**/*.md
    profiles:
      - test
      - v2
    stdin_open: true
    tty: true
    volumes:
      # Site configuration files.
      - type: bind
        source: .
        target: /src
        read_only: true
      # Files shared between host and container and writeable by both.
      - type: bind
        source: ./test/shared
        target: /shared
      - type: bind
        source: ./content/influxdb/v2/.env.test
        target: /app/.env.test
        read_only: true
      # In your code samples, use `/app/data/<FILE.lp>` or `data/<FILE.lp>` to access sample data files from the `static/downloads` directory. 
      - type: bind
        source: ./static/downloads
        target: /app/data
        read_only: true
      # In your code samples, use `/app/iot-starter` to store example modules or project files.
      - type: volume
        source: v2-tmp
        target: /app/iot-starter
      # Target directory for the content under test.
      # Files are copied from /src/content/<productpath> to /app/content/<productpath> before running tests.
      - type: volume
        source: test-content
        target: /app/content
    working_dir: /app
volumes:
  test-content:
  cloud-tmp:
  cloud-dedicated-tmp:
  cloud-serverless-tmp:
  clustered-tmp:
  telegraf-tmp:
  v2-tmp: